# Generated by Django 3.1.7 on 2021-03-21 23:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='pages/about/')),
                ('image_2', models.ImageField(upload_to='pages/about/')),
                ('image_3', models.ImageField(upload_to='pages/about/')),
                ('image_4', models.ImageField(upload_to='pages/about/')),
                ('section_1', ckeditor.fields.RichTextField()),
                ('section_2', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('header_image', models.ImageField(null=True, upload_to='pages/finance/')),
                ('image_2', models.ImageField(null=True, upload_to='pages/finance/')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Financing Page',
                'verbose_name_plural': 'Financing Page',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.core')),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Page',
            },
            bases=('pages.core',),
        ),
    ]
