# Generated by Django 3.1.7 on 2021-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_finance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Us Page', 'verbose_name_plural': 'About Us Page'},
        ),
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': 'Financing Page', 'verbose_name_plural': 'Financing Page'},
        ),
        migrations.AlterModelOptions(
            name='residential',
            options={'verbose_name': 'Residential Page', 'verbose_name_plural': 'Residential Page'},
        ),
        migrations.AddField(
            model_name='finance',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
