# Generated by Django 3.1.7 on 2021-03-18 16:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_servicespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_1', models.ImageField(upload_to='pages/about/')),
                ('image_2', models.ImageField(upload_to='pages/about/')),
                ('image_3', models.ImageField(upload_to='pages/about/')),
                ('image_4', models.ImageField(upload_to='pages/about/')),
                ('section_1', ckeditor.fields.RichTextField()),
                ('section_2', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
    ]
