# Generated by Django 3.1.7 on 2021-03-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
