# Generated by Django 3.1.7 on 2021-03-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='image',
        ),
        migrations.AddField(
            model_name='finance',
            name='header_image',
            field=models.ImageField(null=True, upload_to='pages/finance/'),
        ),
        migrations.AddField(
            model_name='finance',
            name='image_2',
            field=models.ImageField(null=True, upload_to='pages/finance/'),
        ),
    ]
