# Generated by Django 3.1.7 on 2021-03-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooling',
            options={'verbose_name': 'Cooling', 'verbose_name_plural': 'Cooling'},
        ),
        migrations.AlterModelOptions(
            name='heating',
            options={'verbose_name': 'Heating', 'verbose_name_plural': 'Heating'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
