# Generated by Django 3.1.7 on 2021-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('emil', models.EmailField(max_length=254)),
                ('zip_code', models.PositiveIntegerField()),
                ('Question', models.TextField()),
            ],
        ),
    ]
