# Generated by Django 3.1.7 on 2021-03-12 16:59

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(verbose_name='Is your heating and air conditioning system operating & maintaining a comfortable temperature?')),
                ('home_temperature', models.IntegerField(verbose_name='What is the temperature of your home?')),
                ('field_of_interest', multiselectfield.db.fields.MultiSelectField(choices=[('Repair', 'Repair'), ('Maintenance', 'Maintenance'), ('Replacement / New install of equipment', 'Replacement / New install of equipment'), ('Other', 'Other')], max_length=63, verbose_name='Are you interested in?')),
                ('issue_of_concern', multiselectfield.db.fields.MultiSelectField(choices=[('Furnace', 'Furnace'), ('Air Conditioner', 'Air Conditioner'), ('Heat Pump-Ducted', 'Heat Pump-Ducted'), ('Heat Pump-Ductless Mini Split', 'Heat Pump-Ductless Mini Split'), ('Water Heater-Tank', 'Water Heater-Tank'), ('Water Heater-Tankless', 'Water Heater-Tankless'), ('Electronic Air Cleaner (EAC)', 'Electronic Air Cleaner (EAC)'), ('Gas Fireplace', 'Gas Fireplace'), ('Gas Piping', 'Gas Piping')], max_length=164, verbose_name='Regarding what type of equipment or issue of concern:')),
                ('equipment_age', models.CharField(choices=[('0 - 5 years', '0 - 5 years'), ('6 - 10 years', '6 - 10 years'), ('11 - 15 years', '11 - 15 years'), ('16 - 20 years', '16 - 20 years')], max_length=50, verbose_name='Approximate age of equipment')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('emil_address', models.EmailField(max_length=254)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cell_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emil',
            new_name='emil_address',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
