# Generated by Django 3.1.7 on 2021-03-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0002_auto_20210312_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Us Message', 'verbose_name_plural': 'Contact Us Messages'},
        ),
        migrations.AlterModelOptions(
            name='mainrequests',
            options={'verbose_name': 'Received Request', 'verbose_name_plural': 'Received Requests'},
        ),
    ]
