# Generated by Django 3.1.7 on 2021-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0003_auto_20210313_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='second_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
