# Generated by Django 3.1.7 on 2021-03-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0005_auto_20210322_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainrequests',
            old_name='address_line',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='mainrequests',
            old_name='cell_number',
            new_name='cell_phone',
        ),
        migrations.RenameField(
            model_name='mainrequests',
            old_name='contact_number',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='mainrequests',
            old_name='emil_address',
            new_name='emil',
        ),
        migrations.RenameField(
            model_name='mainrequests',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='mainrequests',
            old_name='address',
            new_name='street_address',
        ),
    ]
