# Generated by Django 3.1.7 on 2021-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0006_auto_20210322_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequests',
            name='home_temperature',
            field=models.CharField(max_length=255, verbose_name='What is the temperature of your home?'),
        ),
    ]
