# Generated by Django 3.1.7 on 2021-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0009_auto_20210322_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrequests',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
