# Generated by Django 3.1.7 on 2021-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0010_auto_20210322_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrequests',
            name='request_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
